dominic  = User.create!(fullname: "Dominic", email: "dominic@gmail.com", password: "password", bio: "I like driving.")
jake     = User.create!(fullname: "Jake", email: "jake@gmail.com", password: "password", bio: "I like driving.")
cydnee   = User.create!(fullname: "Cydnee", email: "cydnee@gmail.com", password: "password", bio: "I like driving.")
steven   = User.create!(fullname: "Steven", email: "steven@gmail.com", password: "password", bio: "I like driving.")
alex     = User.create!(fullname: "Alex", email: "alex@gmail.com", password: "password", bio: "I like driving.")

ride1    = Ride.create!(origin: "1719 S Uinta Way, Denver, CO 80231", destination: "320 S Jasmine St, Denver, CO 80224, USA", departure_time: "09:00", user_id: jake.id )
ride2    = Ride.create!(origin: "9182 E Harvard Ave, Denver, CO 80231, USA", destination: "4381 E Montana Pl, Denver, CO 80222, USA", departure_time: "11:00", user_id: cydnee.id )
ride3    = Ride.create!(origin: "8659 E Wesley Dr, Denver, CO 80231, USA", destination: "1832 S Ivanhoe St, Denver, CO 80224, USA", departure_time: "13:00", user_id: dominic.id )
ride4    = Ride.create!(origin: "9142 E Missouri Ave, Denver, CO 80247, USA", destination: "1125 S Kalispell St, Aurora, CO 80017, USA", departure_time: "05:00", user_id: steven.id )
ride5    = Ride.create!(origin: "4381 E Montana Pl, Denver, CO 80222, USA", destination: "9142 E Missouri Ave, Denver, CO 80247, USA", departure_time: "09:00", user_id: alex.id )

friends1 = Friend.create!(receiver_id: dominic.id, requestor_id: jake.id)
friends2 = Friend.create!(receiver_id: dominic.id, requestor_id: cydnee.id, status: 1)
friends3 = Friend.create!(receiver_id: steven.id, requestor_id: dominic.id)
friends4 = Friend.create!(receiver_id: steven.id, requestor_id: jake.id, status: 1)

pinto    = Vehicle.create!(user_id: dominic.id, make: 'Toyota', model: 'Prius', year: '2020')
geometro = Vehicle.create!(user_id: cydnee.id, make: 'Chevy', model: 'Nova', year: '2010')
geostorm = Vehicle.create!(user_id: jake.id, make: 'Ford', model: 'Mustang', year: '2012')
new_car = Vehicle.create!(user_id: steven.id, make: 'Nissan', model: 'Leaf', year: '2015')
new_car = Vehicle.create!(user_id: alex.id, make: 'Chevy', model: 'Volt', year: '2018')

rideday = Rideday.create!(day_of_week: 'Monday', ride_id: ride1.id)
rideday2 = Rideday.create!(day_of_week: 'Monday', ride_id: ride2.id)
rideday3 = Rideday.create!(day_of_week: 'Monday', ride_id: ride3.id)
rideday4 = Rideday.create!(day_of_week: 'Monday', ride_id: ride4.id)
rideday5 = Rideday.create!(day_of_week: 'Monday', ride_id: ride5.id)
rideday6 = Rideday.create!(day_of_week: 'Wednesday', ride_id: ride1.id)
rideday7 = Rideday.create!(day_of_week: 'Wednesday', ride_id: ride2.id)
rideday8 = Rideday.create!(day_of_week: 'Wednesday', ride_id: ride3.id)
rideday9 = Rideday.create!(day_of_week: 'Wednesday', ride_id: ride4.id)
rideday10 = Rideday.create!(day_of_week: 'Wednesday', ride_id: ride5.id)
rideday11 = Rideday.create!(day_of_week: 'Thursday', ride_id: ride1.id)
rideday12 = Rideday.create!(day_of_week: 'Thursday', ride_id: ride2.id)
rideday13 = Rideday.create!(day_of_week: 'Thursday', ride_id: ride3.id)
rideday14 = Rideday.create!(day_of_week: 'Thursday', ride_id: ride4.id)
